package com.fero.skripsi.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class DetailPesanan(
    val alamat_pelanggan: String?,
    val alamat_penjahit: String?,
    val asal_bahan: String?,
    val bahan_jahit: String?,
    val biaya_jahitan: Int?,
    val catatan_pesanan: String?,
    val desain_jahitan: String?,
    val email_pelanggan: String?,
    val email_penjahit: String?,
    val foto_pelanggan: String?,
    val foto_penjahit: String?,
    val gambar_kategori: String?,
    val harga_bahan: Int?,
    val hari_buka: String?,
    val id_detail_kategori: Int?,
    val id_kategori: Int?,
    val id_pelanggan: Int?,
    val id_penjahit: Int?,
    val id_pesanan: Int?,
    val jam_buka: String?,
    val jam_tutup: String?,
    val jangkauan_kategori_penjahit: String?,
    val jk_pelanggan: String?,
    val jumlah_jahitan: Int?,
    val keterangan_kategori: String?,
    val keterangan_toko: String?,
    val lama_waktu_pengerjaan: String?,
    val latitude_pelanggan: String?,
    val latitude_penjahit: String?,
    val lebar_bahan: Int?,
    val longitude_pelanggan: String?,
    val longitude_penjahit: String?,
    val nama_kategori: String?,
    val nama_pelanggan: String?,
    val nama_penjahit: String?,
    val nama_toko: String?,
    val ongkos_penjahit: Int?,
    val panjang_bahan: Int?,
    val password_pelanggan: String?,
    val password_penjahit: String?,
    val perkiraan_lama_waktu_pengerjaan: String?,
    val spesifikasi_penjahit: String?,
    val status_bahan: String?,
    val status_pesanan: String?,
    val tanggal_pesanan: String?,
    val tanggal_pesanan_selesai: String?,
    val telp_pelanggan: String?,
    val telp_penjahit: String?,
    val total_biaya: Int?
) : Parcelable